### ISSUE TITLE
detect jquery textcomplete keyup event

### ISSUE THREAD

**Issue by leizard** [yuku-t/jquery-textcomplete#211]
Hi, thank you for the great work.
My textarea have the keyup enter event which allow user to submit on enter. The issue is it also catchs the enter event when I select from textcomplete dropdown list and submit the value right away.
How could I resolve this ?
Thank you.

**Comment by yuku-t** [comment]
hmmm, i think there is no beautiful way to solve the probelm :cry: If i'm on your situation, i'll do as follows:

the plugin issues `textComplete:show` and `textComplete:hide` events when a dropdown is shown and hidden respectively. By using them, you can know whether the dropdown is shown or not. But the problem is that `textComplete:hide` event is issued on keydown event, which prior to keyup event. This means that, you have to turn off a flag (`dropdownshown` in following sample) asynchronously.

```js
$('#textarea')
    .textcomplete([/* ... */])
    .on('textComplete:show', function () {
        $(this).data('dropdownshown', true);
    })
    .on('textComplete:hide', function () {
        var self = this;
        setTimeout(function () {
            $(self).data('dropdownshown', false);
        }, 100);
    });

function yourKeyupEventHandler(e) {
    if (!$('#textarea').data('dropdownshown')) {
        submit();
    }
}
```

**Comment by leizard** [comment]
Thank you for your quick reply. This workaround works for me too (I'm working with a Meteor project). You saved my day. Thank you.

**Comment by githubdoramon** [comment]
Also worked for me... perfect!

**Comment by yuku-t** [comment]
yey
