### ISSUE TITLE
Allow different options per strategy

### ISSUE THREAD

**Issue by marcvangend** [yuku-t/jquery-textcomplete#223]
Currently, the option object is defined once for all strategies. I would like to be able to apply different options per strategy.

To illustrate my request with a use case:
I have a text area with two strategies: mentions and emoji's. For the emoji's, I want to show max 25 instead of 10 search results and display the emoji's as a 5x3 grid instead of a normal list. This would be pretty easy if I could `maxCount` and `className` options for just the emoji strategy.

**Comment by yuku-t** [comment]
Hi @marcvangend, thanks for the issue.

Because options have a responsibility to represent a dropdown's behavior, I feel something strange if parameters, which represent a strategy's behavior, have `className`. So, I added "id" parameter instead. Now if "id" parameter is given, textcomplete sets the value to dropdown element's "data-strategy" attribute.

![image](https://cloud.githubusercontent.com/assets/96157/13903433/7a9b466e-eebe-11e5-8e7b-de013e6a23ac.png)

Thus you can change style by:

```css
.textcomplete-dropdown[data-strategy='emoji'] {
   // 
}
```

When it comes to `maxCount`, you can implement it super easily:

```js
textcomplete([
  {
    id: 'emoji'
    search: function (term, callback) {
      var values = // your code
      callback(values.slice(0, 25));
    },
  },
  {
    id: 'mention',
    search: function (term, callback) {
      var values = // your code
      callback(values.slice(0, 10));
    }
  }
], {
  maxCount: Infinity
})
```
